<a href="https://colab.research.google.com/github/choiminji-020102/NLP_project/blob/main/%EC%8B%A4%EC%8A%B507_231004.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## SentenceBERT를 이용한 문장 유사도 측정

In [ ]:
### 필요한 라이브러리 설치 : sentence_transformers (하드디스크에 설치)
!pip install sentence_transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 56.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 62.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 295.0/295.0 kB 28.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.8/3.8 MB 56.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 28.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 23.6 MB/s eta 0:00:00
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125923 sha256=bba286cec0adbd798660c917111a3e1bb04cf9a01fd59a4e85cf49b607e2bcb3
  Stored in directory: /root/.cache/pip/wheels/62/f2/10/1e606fd5f02395388f74e7462910fe851042f97238cbbd902f
Successfully built sentence_transformers


In [ ]:
### 필요한 라이브러리 임폴트 (RAM에 올려둠)
from sentence_transformers import SentenceTransformer

### 한글 문장 유사도 측정

In [ ]:
### 문장 임베딩 벡터 추출 --> 파인 튜닝한 한국어 SentenceBERT(SentenceTransformer) 모델 생성
model_name = 'ddobokki/klue-roberta-base-nli-sts'
model_kor = SentenceTransformer(model_name)

In [ ]:
### 한글 텍스트 데이터 생성
ko_sentences = ['직원이 무단 퇴사를 했는데 손해 배상 청구할 수 있나요?', '무단 퇴사한 직원에 대한 손해 배상 청구가 가능한가요?']

In [ ]:
### 문장 임베딩 벡터 생성하기
embeddings = model_kor.encode(ko_sentences)

# 결과 확인하기
print(f'실습용 문장의 임베딩 행렬의 모양 : {embeddings.shape}')
print('-'*80)
print(f'실습용 문장 1의 임베딩 벡터 : \n{embeddings[0]}')
print('-'*80)
print(f'실습용 문장 2의 임베딩 벡터 : \n{embeddings[1]}')

실습용 문장의 임베딩 벡터 : 
(2, 768)
--------------------------------------------------------------------------------
실습용 문장 1 : 
[-4.99942571e-01 -3.59200835e-01 -7.38402531e-02  4.84219283e-01
 -4.96614248e-01  5.82403541e-01 -4.56283726e-02 -3.81823957e-01
 -3.94545138e-01  2.18352810e-01  2.40236789e-01 -6.53119922e-01
  1.17322057e-01 -4.41113472e-01 -8.18792358e-03 -2.16762990e-01
  1.42985918e-02 -9.46455747e-02  1.55718908e-01 -1.03794202e-01
 -5.95203459e-01 -5.41155756e-01 -6.22601569e-01 -1.00601912e+00
 -2.20479086e-01 -1.32809609e-01 -4.36401814e-02 -4.01161388e-02
  5.56914985e-01  7.56343365e-01  6.72926083e-02  8.65490139e-01
  4.12386395e-02  2.79035717e-01 -1.98161840e-01 -5.00128530e-02
  3.10567111e-01 -3.46614331e-01 -6.20579302e-01  6.81772709e-01
  8.81860033e-02  2.54626155e-01 -4.60292697e-01 -1.45168155e-01
 -6.55795122e-03 -2.85244942e-01  6.48579188e-03  3.51094782e-01
  9.55613628e-02 -1.56446829e-01 -1.90832376e-01 -3.73097628e-01
  2.39245042e-01  3.94674800e-02 -3

In [ ]:
### 코사인 유사도 측정

# 필요한 함수 임폴트
from sklearn.metrics.pairwise import cosine_similarity

# 1차원 배열 --> 2차원 행렬로 변환
embedding1 = embeddings[0].reshape((1,768))
embedding2 = embeddings[1].reshape((1,768))

# cosine_similarity 함수 사용
sim = cosine_similarity(embedding1, embedding2)

# 결과 확인하기
print(sim)

[[0.96061534]]


### 영어 문장 유사도 측정

In [ ]:
### 영어로 파인 튜닝된 SentenceBERT 모델 생성
model_name = 'sentence-transformers/all-MiniLM-L12-v2'
model_eng = SentenceTransformer(model_name)

In [ ]:
### 영문 텍스트 데이터 생성
eng_sentences = ["What should I do to be a great scientist?", "How can I be a good scientist?"]
print(eng_sentences)

['What should I do to be a great scientist?', 'How can I be a good scientist?']


In [ ]:
### 문장 임베딩 벡터 생성하기
embeddings = model_eng.encode(en_sentences)

# 결과 확인하기
print(f'실습용 문장의 임베딩 행렬의 모양 : {embeddings.shape}')
print('-'*80)
print(f'실습용 문장 1의 임베딩 벡터 : \n{embeddings[0]}')
print('-'*80)
print(f'실습용 문장 2의 임베딩 벡터 : \n{embeddings[1]}')

실습용 문장의 임베딩 행렬의 모양 : 
(2, 384)
--------------------------------------------------------------------------------
실습용 문장 1 : 
[ 2.22636163e-02  8.50509629e-02  7.91068599e-02 -6.84864074e-03
 -1.46627463e-02 -6.85858354e-02  2.64204349e-02  6.64388910e-02
 -4.24608253e-02 -3.75801958e-02  1.80893745e-02 -9.48859900e-02
 -4.75542396e-02  7.65434429e-02 -3.93009633e-02  2.58018598e-02
 -7.41134211e-02  5.87385967e-02  3.13342884e-02 -7.86113665e-02
 -6.38961121e-02  4.31189574e-02  6.02598302e-03  1.21794816e-03
 -5.90102486e-02  8.42711702e-02 -2.48904601e-02 -6.01979792e-02
  2.75624543e-02 -5.94474003e-02 -8.06285942e-04 -7.62991086e-02
  1.78552195e-02  2.06335429e-02 -3.27370800e-02  4.25934419e-02
  6.07815199e-02 -2.56904643e-02  5.79138026e-02  5.28666861e-02
  9.59739275e-03 -4.70351726e-02  2.61405464e-02 -9.10800532e-04
  8.14124290e-03 -1.69612709e-02  2.88743880e-02 -1.83994416e-03
  3.87182906e-02  3.14612091e-02 -5.87458573e-02 -7.69814849e-02
 -1.39820710e-01 -6.15611114e-0

In [ ]:
### 코사인 유사도 측정

# 1차원 배열 --> 2차원 행렬로 변환
embedding1 = embeddings[0].reshape((1,384))
embedding2 = embeddings[1].reshape((1,384))

# cosine_similarity 함수 사용
sim = cosine_similarity(embedding1, embedding2)

# 결과 확인하기
print(sim)

[[0.8954653]]


### 영어 / 한글 문장 유사도 측정

In [ ]:
### 다국어 지원 SentenceBERT 모델 생성
model_name='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'
model_multi = SentenceTransformer(model_name)

In [ ]:
### 텍스트 데이터 생성
sentences = ['What should I do to be a great scientist?', '훌륭한 과학자가 되려면 어떻게 해야 할까요?']

In [ ]:
### 문장 임베딩 벡터 생성하기
embeddings = model_multi.encode(sentences)

# 결과 확인하기
print(f'실습용 문장의 임베딩 행렬의 모양 : {embeddings.shape}')
print('-'*80)
print(f'실습용 문장 1의 임베딩 벡터 : \n{embeddings[0]}')
print('-'*80)
print(f'실습용 문장 2의 임베딩 벡터 : \n{embeddings[1]}')

실습용 문장의 임베딩 행렬의 모양 : 
(2, 384)
--------------------------------------------------------------------------------
실습용 문장 1 : 
[ 5.46488203e-02  4.94343251e-01  4.10707593e-01  1.27668083e-01
 -9.11792293e-02 -5.76901734e-01  1.17372675e-02  1.73615143e-01
 -3.01463693e-01 -1.61016673e-01 -2.14112010e-02 -7.54894078e-01
 -1.01586759e-01  2.17390079e-02 -2.76769996e-01  4.08532843e-03
 -1.66494563e-01 -1.53407618e-01  9.10674408e-03 -2.29964718e-01
 -4.85452652e-01  1.59717634e-01  7.86594078e-02 -1.78895891e-01
 -2.89161235e-01  2.65021116e-01 -1.87272504e-01 -2.74408847e-01
  8.98739174e-02 -1.40582860e-01  1.85040031e-02 -8.13296661e-02
  2.98329979e-01  1.22198788e-02  8.52153525e-02  4.40637112e-01
 -3.57331261e-02 -2.71989942e-01  3.55497718e-01  2.01634899e-01
  3.68284702e-01  8.60847458e-02  6.20844901e-01  1.44933268e-01
 -1.14840753e-01 -4.09185201e-01 -2.46176887e-02 -2.33240739e-01
  7.04460591e-02  2.04685375e-01 -2.15648532e-01 -1.35802731e-01
 -4.60398763e-01 -4.50309187e-0

In [ ]:
### 코사인 유사도 측정

# 1차원 배열 --> 2차원 행렬로 변환
embedding1 = embeddings[0].reshape((1,384))
embedding2 = embeddings[1].reshape((1,384))

# cosine_similarity 함수 사용
sim = cosine_similarity(embedding1, embedding2)

# 결과 확인하기
print(sim)

[[0.9493034]]


## 문장 유사도를 이용한 추천 시스템

In [ ]:
## 구글 colab과 내 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
### pd.read_csv() --> DataFrame 자료형 데이터 생성

# 필요한 라이브러리 임폴트
import pandas as pd

# 파일 경로 설정
file_path = '/content/drive/MyDrive/Colab Notebooks/딥러닝/데이터/movies_metadata.csv'

# DataFrame 자료형 생성
df_movies = pd.read_csv(file_path)

# 결과 확인하기
print(df_movies)

       adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1      False                                                NaN  65000000   
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3      False                                                NaN  16000000   
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
...      ...                                                ...       ...   
45461  False                                                NaN         0   
45462  False                                                NaN         0   
45463  False                                                NaN         0   
45464  False                                                NaN         0   
45465  False                                                NaN         0   

                                                  genres  \
0      [{'id': 

<ipython-input-14-d849df28b770>:10: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df_movies = pd.read_csv(file_path)


In [ ]:
### 기본 정보 확인 --> df.info()
df_movies.info()

# overview : 44512개
# title : 45460개
# => 누락 데이터 제거 필요!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   adult                  45466 non-null  object 
 1   belongs_to_collection  4494 non-null   object 
 2   budget                 45466 non-null  object 
 3   genres                 45466 non-null  object 
 4   homepage               7782 non-null   object 
 5   id                     45466 non-null  object 
 6   imdb_id                45449 non-null  object 
 7   original_language      45455 non-null  object 
 8   original_title         45466 non-null  object 
 9   overview               44512 non-null  object 
 10  popularity             45461 non-null  object 
 11  poster_path            45080 non-null  object 
 12  production_companies   45463 non-null  object 
 13  production_countries   45463 non-null  object 
 14  release_date           45379 non-null  object 
 15  re

In [ ]:
### 줄거리, 제목 컬럼 --> 팬시 인덱싱
data = df_movies.loc[:, ['overview', 'title']]

# 결과 확인하기
print(data)

                                                overview  \
0      Led by Woody, Andy's toys live happily in his ...   
1      When siblings Judy and Peter discover an encha...   
2      A family wedding reignites the ancient feud be...   
3      Cheated on, mistreated and stepped on, the wom...   
4      Just when George Banks has recovered from his ...   
...                                                  ...   
45461        Rising and falling between a man and woman.   
45462  An artist struggles to finish his work while a...   
45463  When one of her hits goes wrong, a professiona...   
45464  In a small town live two brothers, one a minis...   
45465  50 years after decriminalisation of homosexual...   

                             title  
0                        Toy Story  
1                          Jumanji  
2                 Grumpier Old Men  
3                Waiting to Exhale  
4      Father of the Bride Part II  
...                            ...  
45461               

In [ ]:
### 누락 '행' 제거 --> dropna(axis=0)
df_cleaned = data.dropna()

# 결과 확인하기
print(df_cleaned)
print('-'*80)
print(f'각 컬럼 별 누락 데이터의 수 : \n{df_cleaned.isnull().sum()}')

                                                overview  \
0      Led by Woody, Andy's toys live happily in his ...   
1      When siblings Judy and Peter discover an encha...   
2      A family wedding reignites the ancient feud be...   
3      Cheated on, mistreated and stepped on, the wom...   
4      Just when George Banks has recovered from his ...   
...                                                  ...   
45461        Rising and falling between a man and woman.   
45462  An artist struggles to finish his work while a...   
45463  When one of her hits goes wrong, a professiona...   
45464  In a small town live two brothers, one a minis...   
45465  50 years after decriminalisation of homosexual...   

                             title  
0                        Toy Story  
1                          Jumanji  
2                 Grumpier Old Men  
3                Waiting to Exhale  
4      Father of the Bride Part II  
...                            ...  
45461               

In [ ]:
### 누락 데이터 제거 후 인덱스 재조정 --> df.reset_index(drop=True, inplace=True)
df_cleaned.reset_index(drop=True, inplace=True)

# 결과 확인하기
print(df_cleaned)

                                                overview  \
0      Led by Woody, Andy's toys live happily in his ...   
1      When siblings Judy and Peter discover an encha...   
2      A family wedding reignites the ancient feud be...   
3      Cheated on, mistreated and stepped on, the wom...   
4      Just when George Banks has recovered from his ...   
...                                                  ...   
44501        Rising and falling between a man and woman.   
44502  An artist struggles to finish his work while a...   
44503  When one of her hits goes wrong, a professiona...   
44504  In a small town live two brothers, one a minis...   
44505  50 years after decriminalisation of homosexual...   

                             title  
0                        Toy Story  
1                          Jumanji  
2                 Grumpier Old Men  
3                Waiting to Exhale  
4      Father of the Bride Part II  
...                            ...  
44501               

In [ ]:
### data의 수를 20000개로 축소
df_data = df_cleaned.iloc[0:20000, :]

# 결과 확인하기
print(df_data)

                                                overview  \
0      Led by Woody, Andy's toys live happily in his ...   
1      When siblings Judy and Peter discover an encha...   
2      A family wedding reignites the ancient feud be...   
3      Cheated on, mistreated and stepped on, the wom...   
4      Just when George Banks has recovered from his ...   
...                                                  ...   
19995  Arkin escapes with his life from the vicious g...   
19996  Remake of a hit film from 1990, "The Cherry Or...   
19997  Chronicles the adventures of Franklin Delano R...   
19998  Masked vigilantes Charge (Jason Trost), Cutthr...   
19999   Part one of a BBC documentary about Jean Renoir.   

                                                   title  
0                                              Toy Story  
1                                                Jumanji  
2                                       Grumpier Old Men  
3                                      Wait

In [ ]:
### SentenceBERT 모델 생성
model_name = 'sentence-transformers/all-MiniLM-L12-v2'
model = SentenceTransformer(model_name)

NameError: ignored

In [ ]:
### 문장 임베딩 벡터 생성

# overview 컬럼 --> df_data.overview.values
sentences = df_data.overview.values  # df_data['overview'].values와 같음
print(f'overview 컬럼에서 추출한 값 확인 : \n{sentences}')

print('-'*80)

# model.encode() 함수 사용
embeddings = model.encode(sentences)

# 결과 확인하기
print(f'생성된 문장 임베딩 행렬의 모양 : {embeddings.shape}')
print('-'*80)
print(f'문장 1개의 임베딩 벡터의 모양 : {embeddings[0].shape}')

overview 컬럼에서 추출한 값 확인 : 
["Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."
 "When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures."
 "A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interes

In [ ]:
### 문장 임베딩 행렬 저장

# 필요한 라이브러리 임폴트
import numpy as np

# 데이터 저장
np.save('/content/drive/MyDrive/Colab Notebooks/딥러닝/nlp/embeddings.npy', embeddings)

In [ ]:
### 저장된 넘파이 배열(임베딩 행렬) 불러오기

# 필요한 라이브러리 임폴트
import numpy as np
import pandas as pd

# 파일 경로 설정
file_path = '/content/drive/MyDrive/Colab Notebooks/딥러닝/nlp/embeddings.npy'

# 저장된 넘파이 배열 불러오기
embeddings = np.load(file_path)

# 결과 확인하기
print(f'문장 임베딩 행렬의 모양 : {embeddings.shape}')

문장 임베딩 행렬의 모양 : (20000, 384)


In [ ]:
### linear_kernel() 함수 --> 20000개의 영화 줄거리 각각에 대해서 코사인 유사도 측정
# 코사인 유사도를 대신함. 집단적으로 계산할 때 사용함.

# 필요한 함수 임폴트
from sklearn.metrics.pairwise import linear_kernel

# 20000개의 영화 줄거리간의 코사인 유사도 계산 --> 유사도 행렬(자료형 : 데이터프레임) 생성
sim_matrix = linear_kernel(embeddings, embeddings)

# 결과 확인하기
print(f'유사도 측정의 결과 : \n{sim_matrix}')
print('-'*80)
print(f'유사도 측정의 결과 값의 모양 : {sim_matrix.shape}')
print('-'*80)
print(f'Toy Story에 대한 유사도 측정의 결과 : \n{sim_matrix[:, 0]}')

유사도 측정의 결과 : 
[[1.         0.33839947 0.12692963 ... 0.15745524 0.01629961 0.01816789]
 [0.33839947 1.0000002  0.26377776 ... 0.18450312 0.2100673  0.15408282]
 [0.12692963 0.26377776 1.0000001  ... 0.05679224 0.12085309 0.10428731]
 ...
 [0.15745524 0.18450312 0.05679224 ... 1.0000001  0.22642896 0.29066998]
 [0.01629961 0.2100673  0.12085309 ... 0.22642896 1.         0.17841542]
 [0.01816789 0.15408282 0.10428731 ... 0.29066998 0.17841542 1.0000001 ]]
--------------------------------------------------------------------------------
유사도 측정의 결과 값의 모양 : (20000, 20000)
--------------------------------------------------------------------------------
Toy Story에 대한 유사도 측정의 결과 : 
[1.         0.33839947 0.12692963 ... 0.15745524 0.01629961 0.01816789]


In [ ]:
df_data.title

In [ ]:
### 코사인 유사도 행렬 --> 데이터프레임 생성

# 데이터프레임 생성
columns = df_data.title.values
index = df_data.title.values

df_sim = pd.DataFrame(data=sim_matrix, columns=columns, index=index)

# 결과 확인하기
df_sim

Toy Story   Jumanji  \
Toy Story                                            1.000000  0.338399   
Jumanji                                              0.338399  1.000000   
Grumpier Old Men                                     0.126930  0.263778   
Waiting to Exhale                                    0.175748  0.205652   
Father of the Bride Part II                          0.137818  0.144077   
...                                                       ...       ...   
The Collection                                       0.121312  0.273338   
The Cherry Orchard: Blossoming                       0.091254  0.244045   
FDR: American Badass!                                0.157455  0.184503   
All Superheroes Must Die                             0.016300  0.210067   
Jean Renoir: Part One - From La Belle Époque to...   0.018168  0.154083   

                                                    Grumpier Old Men  \
Toy Story                                                   0.126930   
Jumanji                                                     0.263778   
Grumpier Old Men                                            1.000000   
Waiting to Exhale                                           0.360031   
Father of the Bride Part II                                 0.175603   
...                                                              ...   
The Collection                                              0.112453   
The Cherry Orchard: Blossoming                              0.178710   
FDR: American Badass!                                       0.056792   
All Superheroes Must Die                                    0.120853   
Jean Renoir: Part One - From La Belle Époque to...          0.104287   

                                                    Waiting to Exhale  \
Toy Story                                                    0.175748   
Jumanji                                                      0.205652   
Grumpier Old Men                                             0.360031   
Waiting to Exhale                                            1.000000   
Father of the Bride Part II                                  0.204694   
...                                                               ...   
The Collection                                               0.248840   
The Cherry Orchard: Blossoming                               0.070290   
FDR: American Badass!                                        0.161954   
All Superheroes Must Die                                     0.278832   
Jean Renoir: Part One - From La Belle Époque to...           0.182142   

                                                    Father of the Bride Part II  \
Toy Story                                                              0.137818   
Jumanji                                                                0.144077   
Grumpier Old Men                                                       0.175603   
Waiting to Exhale                                                      0.204694   
Father of the Bride Part II                                            1.000000   
...                                                                         ...   
The Collection                                                         0.232690   
The Cherry Orchard: Blossoming                                         0.095708   
FDR: American Badass!                                                  0.023649   
All Superheroes Must Die                                               0.118189   
Jean Renoir: Part One - From La Belle Époque to...                     0.201691   

                                                        Heat   Sabrina  \
Toy Story                                           0.224320  0.183411   
Jumanji                                             0.294304  0.253075   
Grumpier Old Men                                    0.211339  0.314121   
Waiting to Exhale                                   0.286783  0.332937   
Father of the Bride Part II               

In [ ]:
### 특정 영화 기준 --> 줄거리가 유사한 영화 추천 함수 생성

def recommend(title):
  top10 = df_sim.loc[:, title].sort_values(ascending=False).iloc[1:11]
  return top10

# 결과 확인하기
top10 = recommend('GoldenEye')
print(f'결과 확인하기 : \n{top10}')

결과 확인하기 : 
Live and Let Die               0.628484
Octopussy                      0.618100
Never Say Never Again          0.605646
The Living Daylights           0.594822
The Man with the Golden Gun    0.591555
Goldfinger                     0.573768
Casino Royale                  0.573743
Licence to Kill                0.571086
Die Another Day                0.567978
Dr. No                         0.553751
Name: GoldenEye, dtype: float32
